const STATUS_CREATED = 201;
const STATUS_BAD_REQUEST = 400;
const STATUS_UNAUTHORIZED = 401;
const STATUS_FORBIDDEN = 403;
const STATUS_NOT_FOUND = 404;
const STATUS_CONFLICT = 409;
const STATUS_INTERNAL_SERVER_ERROR = 500;

const BAD_REQUEST_MESSAGE = "Dados inválidos.";
const UNAUTHORIZED_MESSAGE = "Autorização necessária.";
const FORBIDDEN_MESSAGE = "Você não tem permissão para realizar esta ação.";
const NOT_FOUND_MESSAGE = "Recurso não encontrado.";
const CONFLICT_MESSAGE = "Este e-mail já está cadastrado.";
const INTERNAL_SERVER_ERROR_MESSAGE = "Erro interno do servidor.";

module.exports = {
  STATUS_CREATED,
  STATUS_BAD_REQUEST,
  STATUS_UNAUTHORIZED,
  STATUS_FORBIDDEN,
  STATUS_NOT_FOUND,
  STATUS_CONFLICT,
  STATUS_INTERNAL_SERVER_ERROR,
  BAD_REQUEST_MESSAGE,
  UNAUTHORIZED_MESSAGE,
  FORBIDDEN_MESSAGE,
  NOT_FOUND_MESSAGE,
  CONFLICT_MESSAGE,
  INTERNAL_SERVER_ERROR_MESSAGE,
};
